### ISSUE TITLE
buster-server fails on headless mode on Windows 8

### ISSUE THREAD

**Issue by atlefren** [busterjs/buster#434]
os: Windows 8 enterprise

When trying to run buster-server with the -c option (for headless mode on win8) an error occurs and the process dies, but things work just fine without the -c option.

```
C:\>buster -v
Buster.JS version 0.7.17 Beta 5

C:\>phantomjs -v
1.9.8

C:\>buster-server -c
Starting headless browser...
buster-server running on http://localhost:1111

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)

C:\>buster-server
buster-server running on http://localhost:1111
```

This works as excpected on  Ubuntu 14.10:

```
atlefren@marjory:~$ buster -v
Buster.JS version 0.7.8 Beta 5
atlefren@marjory:~$ phantomjs -v
1.9.8
atlefren@marjory:~$ buster-server -c -p 1112
Starting headless browser...
buster-server running on http://localhost:1112
Browser was captured.
```

**Comment by atlefren** [comment]
@dwittner Sorry for the delay, extended vacation to blame. 

Will check as soon as possible, thanks for following up!

**Comment by atlefren** [comment]
@dwittner

I installed phantomjs using npm, and haven't been using it for anything else. 

The "phanthomjs -v" command returns a version number (as above), and "phantomjs" gives me an interactive prompt, that seems to be working fine.

My npm packages seems to be in "C:\Users\Atle\AppData\Roaming\npm", which is on my PATH. This is the same directory as buster is installed in.

**Comment by atlefren** [comment]
Ah!

Finally I got to the root cause of this. It seems like buster-server and phantomjs doesn't play nice on Windows when phantomjs is installed using npm (due to this: https://github.com/joyent/node/issues/2318) 

So, the solution was to uninstall the phantomjs installed via npm and install a phantomjs.exe file. 

(this is probably a known thing for node-windows users, but as this worked fine on Linux I could not understand why it didn't work on windows). Maybe worth adding to the readme if it isn't already there?

**Comment by dwittner** [comment]
Thanks for the info. I will try to find a way phantomjs from npm can also be used on windows.

**Comment by dominykas** [comment]
The solution is to use `cross-spawn-async` - but I have to revisit the `phantom-proxy` - I think it's not really needed and things can be simplified.

I also need to get my hands on a proper Windows machine with full dev tools, as phantomjs seems to crash a lot on Appveyor - it could be memory issues or whatever other random stuff.
